2025-08-07 12:51:10 | ✅ API Health-check 성공: {'status': 'ok'}
2025-08-07 12:51:12 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/prepare-data, 페이로드: 없음
2025-08-07 12:51:26 | ✅ 태스크 성공: {'result': 'prepare-data finished'}
2025-08-07 12:51:27 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 12:55:00 | ✅ API Health-check 성공: {'status': 'ok'}
2025-08-07 12:55:01 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/prepare-data, 페이로드: 없음
2025-08-07 12:55:16 | ✅ 태스크 성공: {'result': 'prepare-data finished'}
2025-08-07 12:55:17 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:00:01 | ✅ API Health-check 성공: {'status': 'ok'}
2025-08-07 13:00:01 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/prepare-data, 페이로드: 없음
2025-08-07 13:00:15 | ✅ 태스크 성공: {'result': 'prepare-data finished'}
2025-08-07 13:00:16 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:05:00 | ✅ API Health-check 성공: {'status': 'ok'}
2025-08-07 13:05:01 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/prepare-data, 페이로드: 없음
2025-08-07 13:05:15 | ✅ 태스크 성공: {'result': 'prepare-data finished'}
2025-08-07 13:05:16 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:10:00 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062ed7f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:10:10 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e66d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:10:20 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e8c5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:10:30 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e8cf40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:10:40 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e928b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:10:50 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e8c190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:11:00 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062ed77f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:12:33 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:12:33 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:12:33 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:12:33 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:15:00 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e661f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:15:10 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e66fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:15:21 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e888b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:15:31 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e91250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:15:41 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e91b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:15:51 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e88670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:16:01 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062ed8c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:17:34 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:17:34 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:17:35 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:17:35 | 🚀 API 호출 시작: http://15.164.236.229:8000/run/train, 페이로드: {'model_name': 'movie_predictor'}
2025-08-07 13:20:01 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062ed9520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:20:11 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e87250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:20:21 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e87b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:20:31 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e91520>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:20:41 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e91e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:20:51 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e87670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:21:01 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062f72310>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:25:00 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062ed95b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:25:10 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e862e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:25:20 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e86c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:25:30 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e905b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:25:40 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e90ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:25:50 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e86ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:26:00 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e86550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:30:01 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062ed9640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:30:11 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e86370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:30:21 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e86ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:30:31 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e91640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:30:41 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e91f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:30:51 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e86d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-08-07 13:31:01 | 🚨 API Health-check 중 네트워크 오류 발생: HTTPConnectionPool(host='15.164.236.229', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x763062e865e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
